### ISSUE TITLE
Practiceについて

### ISSUE THREAD

**Issue by t-kusakabe** [r-miyamae/EnglishWordsPractice#2]
# 問題ありそう
- 単語のカードを登録することができない
- カードのマージンが均等でない
- headerがレスポンシブでない
- sectionとは？
# 欲しい機能
- なんばんだ？の攻略用として運用して欲しい

**Comment by gatchan0807** [comment]
- ファイルインポート画面がだっせぇ
- Section の意味がなんとなく違うくない…？

**Comment by r-miyamae** [comment]
@t-kusakabe 
- 単語のカード登録できるようにしました
- マージンとヘッダーはきっと今度やります
- sectionは英単語帳のSectionごとにカード纏めた名残です
- 何番打？の攻略用として具体的な案があれば追加機能として前向きに検討します

**Comment by r-miyamae** [comment]
@ahaha0807 
- うるせえ！！(今度直します)
- sectionは英単語帳のry
